
number_min_genre_occurrence: 150
number_countries: 6

top_revenue_companies: [
        "Walt Disney Pictures",
        "Marvel Studios",
        "Lucasfilm",
        "20th Century Studios",
        "Warner Bros. Pictures",
        "Universal Pictures",
        "Paramount Pictures",
        "Columbia Pictures",
        "Legendary Entertainment",
        "Pixar Animation Studios",
]

star_actors: ["Charlie Chaplin",
        "Clark Gable",
        "Humphrey Bogart",
        "James Stewart",
        "Cary Grant",
        "Marlon Brando",
        "Robert De Niro",
        "Al Pacino",
        "Jack Nicholson",
        "Clint Eastwood",
        "Harrison Ford",
        "Sylvester Stallone",
        "Arnold Schwarzenegger",
        "Tom Hanks",
        "Tom Cruise",
        "Leonardo DiCaprio",
        "Brad Pitt",
        "Johnny Depp",
        "Will Smith",
        "Denzel Washington",
        "George Clooney",
        "Robert Downey Jr.",
        "Chris Hemsworth",
        "Ryan Reynolds",
        "Joaquin Phoenix",
        "Adam Driver",
        "Timothée Chalamet",
        "Chris Evans",
        "Mark Ruffalo",
        "Samuel L. Jackson",
        "Marilyn Monroe",
        "Audrey Hepburn",
        "Katharine Hepburn",
        "Grace Kelly",
        "Elizabeth Taylor",
        "Ingrid Bergman",
        "Meryl Streep",
        "Jane Fonda",
        "Jodie Foster",
        "Sigourney Weaver",
        "Julia Roberts",
        "Nicole Kidman",
        "Cate Blanchett",
        "Sandra Bullock",
        "Cameron Diaz",
        "Angelina Jolie",
        "Charlize Theron",
        "Scarlett Johansson",
        "Jennifer Lawrence",
        "Emma Stone",
    ]